export const HOME_IMAGE_SLIDER_REQUEST = "HOME_IMAGE_SLIDER_REQUEST";
export const HOME_IMAGE_SLIDER_SUCCESS = "HOME_IMAGE_SLIDER_SUCCESS";
export const HOME_IMAGE_SLIDER_ERROR = "HOME_IMAGE_SLIDER_ERROR";


export const CUSTOMER_REVIEW_LIST_REQUEST = "CUSTOMER_REVIEW_LIST_REQUEST";
export const CUSTOMER_REVIEW_LIST_SUCCESS = "CUSTOMER_REVIEW_LIST_SUCCESS";
export const CUSTOMER_REVIEW_LIST_ERROR = "CUSTOMER_REVIEW_LIST_ERROR";

export const CAR_WASH_REQUEST = "CAR_WASH_REQUEST";
export const CAR_WASH_SUCCESS = "CAR_WASH_SUCCESS";
export const CAR_WASH_ERROR = "CAR_WASH_ERROR";


export const PARTNER_LIST_REQUEST = "PARTNER_LIST_REQUEST";
export const PARTNER_LIST_SUCCESS = "PARTNER_LIST_SUCCESS";
export const PARTNER_LIST_EORROR = "PARTNER_LIST_EORROR";


export const CAR_SERVICE_LIST_REQUEST = "CAR_SERVICE_LIST_REQUEST";
export const CAR_SERVICE_LIST_SUCCESS = "CAR_SERVICE_LIST_SUCCESS";
export const CAR_SERVICE_LIST_ERROR = "CAR_SERVICE_LIST_ERROR";

export const CAR_PRODUCT_LIST_REQUEST = "CAR_PRODUCT_LIST_REQUEST";
export const CAR_PRODUCT_LIST_SUCCESS = "CAR_PRODUCT_LIST_SUCCESS";
export const CAR_PRODUCT_LIST_ERROR = "CAR_PRODUCT_LIST_ERROR";

export const SELL_CAR_LIST_REQUEST = "SELL_CAR_LIST_REQUEST";
export const SELL_CAR_LIST_SUCCESS = "SELL_CAR_LIST_SUCCESS";
export const SELL_CAR_LIST_ERROR = "SELL_CAR_LIST_ERROR";

export const BRAND_LIST_REQUEST = "BRAND_LIST_REQUEST";
export const BRAND_LIST_SUCCESS = "BRAND_LIST_SUCCESS";
export const BRAND_LIST_ERROR = "BRAND_LIST_ERROR";

export const MODAL_LIST_REQUEST = "MODAL_LIST_REQUEST";
export const MODAL_LIST_SUCCESS = "MODAL_LIST_SUCCESS";
export const MODAL_LIST_ERROR = "MODAL_LIST_ERROR";

export const Contactus_REQUEST = "Contactus_REQUEST";
export const Contactus_SUCCESS = "Contactus_SUCCESS";
export const Contactus_ERROR = "Contactus_ERROR";

export const GET_QUOTATION_REQUEST = "GET_QUOTATION_REQUEST ";
export const GET_QUOTATION_SUCCESS = "GET_QUOTATION_SUCCESS";
export const GET_QUOTATION_ERROR = "GET_QUOTATION_ERROR";


export const BLOG_REQUEST = "BLOG_REQUEST";
export const BLOG_SUCCESS = "BLOG_SUCCESS";
export const BLOG_ERROR = "BLOG_ERROR";

export const BLOG_READ_REQUEST = "BLOG_READ_REQUEST";
export const BLOG_READ_SUCCESS = "BLOG_READ_SUCCESS";
export const BLOG_READ_ERROR = "BLOG_READ_ERROR";


export const RENT_CAR_REQUEST = "RENT_CAR_REQUEST";
export const RENT_CAR_SUCCESS = "RENT_CAR_SUCCESS";
export const RENT_CAR_ERROR = "RENT_CAR_ERROR";